//! fri3d-fontgen: `artwork/fonts/<name>.bdf` → `fri3d-kernel/src/fonts.rs`.
//!
//! Every font covers ASCII 32..=126. A glyph is its BDF bounding box
//! (rows of `ceil(w/8)` bytes, MSB = leftmost pixel) plus advance and
//! offsets; `fri3d_kernel::font` draws straight from these tables.

use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

const FONTS: &[(&str, &str)] = &[("PIXELIFY_R11", "pixelify_r11.bdf"), ("PIXELIFY_B22", "pixelify_b22.bdf")];
const FIRST: u32 = 32;
const LAST: u32 = 126;

struct Glyph {
    advance: u8,
    w: u8,
    h: u8,
    x_off: i8,
    y_off: i8,
    bits: Vec<u8>,
}

struct Bdf {
    ascent: u8,
    descent: u8,
    glyphs: Vec<Option<Glyph>>,
}

fn main() {
    if let Err(e) = run() {
        eprintln!("fri3d-fontgen: {e}");
        std::process::exit(1);
    }
}

fn run() -> Result<(), String> {
    let root = workspace_root()?;
    let mut out = String::new();
    out.push_str("// Generated by tools/fri3d-fontgen from artwork/fonts/*.bdf. Do not edit.\n\n");
    out.push_str("use crate::font::{BitmapFont, Glyph};\n\n");
    for (name, file) in FONTS {
        let path = root.join("artwork/fonts").join(file);
        let bdf = parse(&fs::read_to_string(&path).map_err(|e| format!("{}: {e}", path.display()))?)?;
        emit(&mut out, name, file, &bdf);
    }
    let dest = root.join("fri3d-kernel/src/fonts.rs");
    fs::write(&dest, out).map_err(|e| format!("{}: {e}", dest.display()))?;
    println!("wrote {}", dest.display());
    Ok(())
}

fn parse(text: &str) -> Result<Bdf, String> {
    let mut ascent = 0u8;
    let mut descent = 0u8;
    let mut glyphs: Vec<Option<Glyph>> = (FIRST..=LAST).map(|_| None).collect();
    let mut lines = text.lines();
    while let Some(line) = lines.next() {
        let mut words = line.split_whitespace();
        match words.next() {
            Some("FONT_ASCENT") => ascent = num(words.next())?,
            Some("FONT_DESCENT") => descent = num(words.next())?,
            Some("STARTCHAR") => {
                let mut encoding: u32 = 0;
                let mut advance: u8 = 0;
                let mut bbx = (0u8, 0u8, 0i8, 0i8);
                let mut bits = Vec::new();
                while let Some(line) = lines.next() {
                    let mut words = line.split_whitespace();
                    match words.next() {
                        Some("ENCODING") => encoding = num(words.next())?,
                        Some("DWIDTH") => advance = num(words.next())?,
                        Some("BBX") => {
                            bbx = (num(words.next())?, num(words.next())?, num(words.next())?, num(words.next())?)
                        }
                        Some("BITMAP") => {
                            let row_bytes = (bbx.0 as usize).div_ceil(8);
                            for _ in 0..bbx.1 {
                                let row = lines.next().ok_or("truncated BITMAP")?.trim();
                                let bytes: Vec<u8> = (0..row.len() / 2)
                                    .map(|i| u8::from_str_radix(&row[i * 2..i * 2 + 2], 16))
                                    .collect::<Result<_, _>>()
                                    .map_err(|e| format!("bitmap row {row}: {e}"))?;
                                bits.extend_from_slice(&bytes[..row_bytes.min(bytes.len())]);
                                bits.resize(bits.len() + row_bytes.saturating_sub(bytes.len()), 0);
                            }
                        }
                        Some("ENDCHAR") => break,
                        _ => {}
                    }
                }
                if (FIRST..=LAST).contains(&encoding) {
                    glyphs[(encoding - FIRST) as usize] = Some(Glyph {
                        advance,
                        w: bbx.0,
                        h: bbx.1,
                        x_off: bbx.2,
                        y_off: bbx.3,
                        bits,
                    });
                }
            }
            _ => {}
        }
    }
    Ok(Bdf { ascent, descent, glyphs })
}

fn num<T: std::str::FromStr>(word: Option<&str>) -> Result<T, String> {
    word.ok_or("missing number")?
        .parse()
        .map_err(|_| format!("bad number {}", word.unwrap_or("")))
}

fn emit(out: &mut String, name: &str, file: &str, bdf: &Bdf) {
    let _ = writeln!(out, "/// {file}: ascent {}, descent {}.", bdf.ascent, bdf.descent);
    let _ = writeln!(out, "pub static {name}: BitmapFont = BitmapFont {{");
    let _ = writeln!(out, "    ascent: {},", bdf.ascent);
    let _ = writeln!(out, "    descent: {},", bdf.descent);
    let _ = writeln!(out, "    glyphs: [");
    for (i, g) in bdf.glyphs.iter().enumerate() {
        let code = FIRST + i as u32;
        let label = if code == 32 { "space".to_string() } else { char::from_u32(code).unwrap().to_string() };
        match g {
            Some(g) => {
                let bits: Vec<String> = g.bits.iter().map(|b| format!("0x{b:02x}")).collect();
                let _ = writeln!(
                    out,
                    "        Glyph {{ advance: {}, w: {}, h: {}, x_off: {}, y_off: {}, bits: &[{}] }}, // {label}",
                    g.advance, g.w, g.h, g.x_off, g.y_off, bits.join(", ")
                );
            }
            None => {
                let _ = writeln!(out, "        Glyph::EMPTY, // {label}");
            }
        }
    }
    let _ = writeln!(out, "    ],");
    let _ = writeln!(out, "}};\n");
}

fn workspace_root() -> Result<PathBuf, String> {
    let out = Command::new("cargo")
        .args(["locate-project", "--workspace", "--message-format=plain"])
        .output()
        .map_err(|e| format!("cargo locate-project: {e}"))?;
    let p = String::from_utf8_lossy(&out.stdout).trim().to_string();
    Path::new(&p)
        .parent()
        .map(Path::to_path_buf)
        .ok_or_else(|| "cannot find workspace root".into())
}
