#!/usr/bin/env bash
# Build every Fri3d app in release mode, wasm-opt-shrink each one, and emit
# firmware/src/embedded_apps.h with a table mapping app IDs to byte arrays.
#
# App IDs match the launcher's compile-time mapping in
# fri3d-app-launcher/src/lib.rs:
#   0 = launcher (special — default boot target)
#   1 = circles
#   2 = mandelbrot
#   3 = test_drawing
#   4 = test_ui
#   5 = snake
#   6 = wifi_pet
#
# Re-run any time a Rust app changes.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO_ROOT"

# (app_crate, underscore_binary_name, id)
declare -a ENTRIES=(
    "fri3d-app-launcher   fri3d_app_launcher      0"
    "fri3d-app-circles    fri3d_app_circles       1"
    "fri3d-app-mandelbrot fri3d_app_mandelbrot    2"
    "fri3d-app-test-drawing fri3d_app_test_drawing 3"
    "fri3d-app-test-ui    fri3d_app_test_ui       4"
    "fri3d-app-snake      fri3d_app_snake         5"
    "fri3d-app-wifi-pet   fri3d_app_wifi_pet      6"
)

mkdir -p firmware/build

echo "[embed-apps] cargo build --release --target wasm32-unknown-unknown (all apps)"
cargo build --release --target wasm32-unknown-unknown $(for row in "${ENTRIES[@]}"; do read -r crate _ _ <<< "$row"; echo -n "-p $crate "; done)

HEADER="firmware/src/embedded_apps.h"

python3 - "$HEADER" "${ENTRIES[@]}" <<'PY'
import pathlib, subprocess, sys
header_path = pathlib.Path(sys.argv[1])

rows = []
for raw in sys.argv[2:]:
    crate, bin_name, id_ = raw.split()
    id_ = int(id_)
    raw_wasm = pathlib.Path(f"target/wasm32-unknown-unknown/release/{bin_name}.wasm")
    opt_wasm = pathlib.Path(f"firmware/build/{bin_name}_opt.wasm")
    # wasm-opt for release-sized binary.
    subprocess.run(["wasm-opt", "-Oz", "--strip-debug", "-o", str(opt_wasm), str(raw_wasm)], check=True)
    data = opt_wasm.read_bytes()
    rows.append((crate, bin_name, id_, data))
    print(f"[embed-apps] {crate} ({id_}): {len(data)} bytes")

lines = [
    "// Auto-generated by firmware/scripts/embed_apps.sh. Do not edit by hand.",
    "",
    "#pragma once",
    "",
    "#include <stdint.h>",
    "",
]
for crate, bin_name, id_, data in rows:
    sym = bin_name.upper()
    lines.append(f"// {crate} (id={id_}): {len(data)} bytes")
    lines.append(f"static const uint8_t {sym}_WASM[] = {{")
    per_row = 12
    for i in range(0, len(data), per_row):
        chunk = ', '.join(f'0x{b:02x}' for b in data[i:i+per_row])
        lines.append(f'    {chunk},')
    lines[-1] = lines[-1].rstrip(',')
    lines.append("};")
    lines.append(f"static const uint32_t {sym}_WASM_LEN = {len(data)};")
    lines.append("")

lines += [
    "struct EmbeddedApp {",
    "    const char*    name;",
    "    uint32_t       app_id;  // 0 = launcher, matches fri3d-app-launcher ids",
    "    const uint8_t* wasm;",
    "    uint32_t       wasm_len;",
    "};",
    "",
    "static const EmbeddedApp EMBEDDED_APPS[] = {",
]
for crate, bin_name, id_, data in rows:
    sym = bin_name.upper()
    human = crate.replace("fri3d-app-", "")
    lines.append(f'    {{"{human}", {id_}, {sym}_WASM, {sym}_WASM_LEN}},')
lines.append("};")
lines.append("static const uint32_t EMBEDDED_APPS_COUNT = sizeof(EMBEDDED_APPS) / sizeof(EMBEDDED_APPS[0]);")
lines.append("")

header_path.write_text('\n'.join(lines))
print(f"[embed-apps] wrote {header_path} ({sum(len(d) for *_, d in rows)} bytes total)")
PY
