//! Run a Fri3d WASM app through the Rust reference runtime and dump the
//! resulting 128×64 framebuffer as a PNG. These PNGs are the golden
//! references that firmware/tools/app-runner/visual_parity.sh diffs the
//! C++ renders against.
//!
//! Using the Rust runtime (not the C++ one) is intentional: if both sides
//! were C++, the parity test would be self-referential. This tool is the
//! bridge that keeps the C++ port honest.
//!
//! Usage:
//!   visual-golden-gen <wasm_path> <out.png> [--frames N] [--seed S]
//!
//! Produces a greyscale 128×64 PNG where 0 = white and 255 = black, matching
//! the palette of tests/visual/apps/*/golden/0.png.

use fri3d_runtime::canvas::Canvas;
use fri3d_runtime::random::Random;
use fri3d_runtime::wasm_runner::WasmRunner;

use std::cell::RefCell;
use std::env;
use std::fs;
use std::path::PathBuf;
use std::rc::Rc;

struct Args {
    wasm_path: PathBuf,
    out_path: PathBuf,
    frames: u32,
    seed: u32,
}

fn parse_args() -> Result<Args, String> {
    let mut it = env::args().skip(1);
    let mut wasm_path: Option<String> = None;
    let mut out_path: Option<String> = None;
    let mut frames: u32 = 1;
    let mut seed: u32 = 42;

    while let Some(arg) = it.next() {
        match arg.as_str() {
            "--frames" => frames = it.next().ok_or("--frames needs a value")?.parse().map_err(|e| format!("--frames: {e}"))?,
            "--seed"   => seed   = it.next().ok_or("--seed needs a value")?.parse().map_err(|e| format!("--seed: {e}"))?,
            a if a.starts_with("--") => return Err(format!("unknown flag {a}")),
            a => {
                if      wasm_path.is_none() { wasm_path = Some(a.to_string()); }
                else if out_path.is_none()  { out_path = Some(a.to_string()); }
                else { return Err(format!("extra positional arg {a}")); }
            }
        }
    }

    let wasm_path = wasm_path.ok_or("missing <wasm_path>")?;
    let out_path = out_path.ok_or("missing <out.png>")?;
    Ok(Args {
        wasm_path: PathBuf::from(wasm_path),
        out_path:  PathBuf::from(out_path),
        frames,
        seed,
    })
}

fn write_png(path: &PathBuf, fb: &[u8]) -> Result<(), String> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|e| format!("mkdir {}: {e}", parent.display()))?;
    }
    let file = fs::File::create(path).map_err(|e| format!("create {}: {e}", path.display()))?;
    let w = std::io::BufWriter::new(file);

    let mut encoder = png::Encoder::new(w, 128, 64);
    encoder.set_color(png::ColorType::Grayscale);
    encoder.set_depth(png::BitDepth::Eight);
    let mut writer = encoder.write_header().map_err(|e| format!("png header: {e}"))?;

    // Canvas buffer is 1 byte per pixel: 0=white, 1=black.
    // Golden PNG convention: 0=black, 255=white — i.e. *inverted*, to match
    // tests/visual/apps/*/golden/0.png which were generated by the old
    // emulator's screenshotter. We follow the same convention so parity
    // against existing goldens keeps working.
    let mut grey = vec![0u8; fb.len()];
    for (i, &b) in fb.iter().enumerate() {
        grey[i] = if b != 0 { 0 } else { 255 };
    }
    writer.write_image_data(&grey).map_err(|e| format!("png data: {e}"))?;
    Ok(())
}

fn main() {
    let args = match parse_args() {
        Ok(a) => a,
        Err(e) => { eprintln!("error: {e}"); eprintln!("usage: visual-golden-gen <wasm> <out.png> [--frames N] [--seed S]"); std::process::exit(2); }
    };

    let wasm = fs::read(&args.wasm_path).unwrap_or_else(|e| {
        eprintln!("read {}: {e}", args.wasm_path.display()); std::process::exit(1);
    });

    let canvas = Rc::new(RefCell::new(Canvas::new()));
    let rng = Rc::new(RefCell::new(Random::new(args.seed)));
    let mut runner = WasmRunner::new();
    runner.set_canvas(canvas.clone());
    runner.set_random(rng.clone());
    // No time provider / app callbacks needed for a still-frame render.

    if !runner.load_module_from_bytes(&wasm) {
        eprintln!("load_module_from_bytes: {}", runner.last_error());
        std::process::exit(1);
    }

    for _ in 0..args.frames {
        runner.call_render();
    }

    let c = canvas.borrow();
    write_png(&args.out_path, c.buffer()).unwrap_or_else(|e| {
        eprintln!("write: {e}"); std::process::exit(1);
    });

    println!("[golden] wrote {} ({}x{}, {} frames, seed {})",
        args.out_path.display(), c.width(), c.height(), args.frames, args.seed);
}
